/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;
/**
 *
 * @author LopezLaps
 */
public class Tac extends javax.swing.JDialog {
 private java.awt.Frame parentFrame = null;
    private boolean b;
   
    /**
     * Creates new form Tac
     * @param parent
     * @param modal
     */
    public Tac(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.parentFrame = parent;
        initComponents();
    }
    public Tac() {
        Themes.Theme.renderAluminium(Tac.class.getName());
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        ta_message = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ta_message.setEditable(false);
        ta_message.setBackground(new java.awt.Color(255, 204, 204));
        ta_message.setColumns(20);
        ta_message.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ta_message.setForeground(new java.awt.Color(255, 0, 153));
        ta_message.setRows(5);
        ta_message.setText("\n         \n         Our creative approach allows us to produce one-of-a-kind \n      images that you will cherished forever. We are passionate \n      about our art and strive to exceed our clients expectations.\n                \n      \n         Our goal is to satisfy our clients photography needs \n      without breaking the bank. Our rate is affordable and we \n      sure it fit for your budgets. Don't hesitate to contact us for \n      further information and let us know if you want our \n      services.\n                \n\n       TERMS AND AGREEMENT:\n                         *300 picture size 3R with album\n                         *one picture size 10R with frame\n                         *for only 10,000 php\n                         *not refunded if you want to cancel");
        jScrollPane1.setViewportView(ta_message);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, 420, 320));

        setSize(new java.awt.Dimension(416, 339));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    
  
    public void Message(){
    String display="Our creative approach allows us to produce one-of-a-kind images that you will"
                + "/ncherished forever. We are passionate about our art and strive to exceed our clients"
                + "/nexpectations."
                + "/n/nOur goal is to satisfy our clients photography needs without breaking the bank."
                + "/nOur rate is affordable and we sure it fit for your budgets. Don't hesitate to contact"
                + "/nus for further information and let us know if you want our services"
                + "/n/nTERMS AND AGREEMENT:"
                + "/n*300 picture sixe 3R with album"
                + "/n*one (10R) with frame"
                + "/n*for only 10,000 php"
                + "/n*not refunded if you want to cancel";
       ta_message.setText(display);
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tac().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea ta_message;
    // End of variables declaration//GEN-END:variables
}
