/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ViewsAdmin;



/**
 *
 * @author LopezLaps
 */
public class Payment extends javax.swing.JFrame {

    /**
     * Creates new form Payment
     */
    public Payment() {
        initComponents();
        Themes.Theme.setIcon(this);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton2 = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btn_bpaymentcancel = new javax.swing.JButton();
        btn_bpaymentdone = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txt_totalamount = new javax.swing.JTextField();
        rb_fullpayment = new javax.swing.JRadioButton();
        rb_deposit = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        txt_change = new javax.swing.JTextField();

        jRadioButton2.setText("jRadioButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setForeground(new java.awt.Color(255, 0, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 153));
        jLabel2.setText("                          PAYMENT ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 340, 20));

        btn_bpaymentcancel.setBackground(new java.awt.Color(255, 0, 153));
        btn_bpaymentcancel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_bpaymentcancel.setForeground(new java.awt.Color(255, 255, 255));
        btn_bpaymentcancel.setText("CANCEL");
        jPanel1.add(btn_bpaymentcancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 110, 30));

        btn_bpaymentdone.setBackground(new java.awt.Color(255, 0, 153));
        btn_bpaymentdone.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_bpaymentdone.setForeground(new java.awt.Color(255, 255, 255));
        btn_bpaymentdone.setText("DONE");
        btn_bpaymentdone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bpaymentdoneActionPerformed(evt);
            }
        });
        jPanel1.add(btn_bpaymentdone, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 100, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 153));
        jLabel1.setText("Total Amount:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));
        jPanel1.add(txt_totalamount, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 200, 30));

        rb_fullpayment.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        rb_fullpayment.setForeground(new java.awt.Color(255, 0, 153));
        rb_fullpayment.setText("FULLPAYMENT");
        jPanel1.add(rb_fullpayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, -1, -1));

        rb_deposit.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        rb_deposit.setForeground(new java.awt.Color(255, 0, 153));
        rb_deposit.setText("DEPOSIT");
        jPanel1.add(rb_deposit, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 153));
        jLabel3.setText("CHANGE:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, -1, -1));
        jPanel1.add(txt_change, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 200, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 370, 250));

        setSize(new java.awt.Dimension(426, 322));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_bpaymentdoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bpaymentdoneActionPerformed
        new ViewsAdmin.Reports().setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_bpaymentdoneActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Payment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_bpaymentcancel;
    private javax.swing.JButton btn_bpaymentdone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton rb_deposit;
    private javax.swing.JRadioButton rb_fullpayment;
    private javax.swing.JTextField txt_change;
    private javax.swing.JTextField txt_totalamount;
    // End of variables declaration//GEN-END:variables
}
