/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ViewsAdmin;

import java.awt.Color;
import javax.swing.ButtonGroup;

/**
 *
 * @author LopezLaps
 */
public class Payment extends javax.swing.JDialog {

    private ViewsAdmin.Reports parentFrame = null;

    private DataObjects.WeddingDetails weddingDetails = null;

    public void setWeddingDetails(DataObjects.WeddingDetails weddingdetails) {
        this.weddingDetails = weddingdetails;
    }

    /**
     * Creates new form Payment
     */
    /**
     * Creates new form NewJDialog
     *
     * @param parent
     * @param modal
     */
    public Payment(ViewsAdmin.Reports parent, boolean modal) {
        super(parent, modal);
        this.parentFrame = parent;
        initComponents();
    }

    public Payment() {

        Themes.Theme.renderAluminium(Payment.class.getName());
        //Themes.Theme.setIcon(this);
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btn_bpaymentcancel = new javax.swing.JButton();
        btn_bpaymentdone = new javax.swing.JButton();
        lbl_amountdeposit = new javax.swing.JLabel();
        txt_amountdeposit = new javax.swing.JTextField();
        lbl_balance = new javax.swing.JLabel();
        txt_balance = new javax.swing.JTextField();

        jRadioButton2.setText("jRadioButton2");

        jRadioButton1.setText("jRadioButton1");

        setTitle("Payment\n");
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setForeground(new java.awt.Color(255, 0, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 153));
        jLabel2.setText("                       DEPOSIT FORM");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 370, 20));

        btn_bpaymentcancel.setBackground(new java.awt.Color(255, 0, 153));
        btn_bpaymentcancel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_bpaymentcancel.setForeground(new java.awt.Color(255, 255, 255));
        btn_bpaymentcancel.setText("CANCEL");
        btn_bpaymentcancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bpaymentcancelActionPerformed(evt);
            }
        });
        jPanel1.add(btn_bpaymentcancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 110, 30));

        btn_bpaymentdone.setBackground(new java.awt.Color(255, 0, 153));
        btn_bpaymentdone.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_bpaymentdone.setForeground(new java.awt.Color(255, 255, 255));
        btn_bpaymentdone.setText("DONE");
        btn_bpaymentdone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bpaymentdoneActionPerformed(evt);
            }
        });
        jPanel1.add(btn_bpaymentdone, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, 100, 30));

        lbl_amountdeposit.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbl_amountdeposit.setForeground(new java.awt.Color(255, 0, 153));
        lbl_amountdeposit.setText("Amount Deposit:");
        jPanel1.add(lbl_amountdeposit, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 100, 100, -1));

        txt_amountdeposit.setBackground(new java.awt.Color(240, 240, 240));
        txt_amountdeposit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_amountdepositKeyPressed(evt);
            }
        });
        jPanel1.add(txt_amountdeposit, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 200, 30));

        lbl_balance.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbl_balance.setForeground(new java.awt.Color(255, 0, 153));
        lbl_balance.setText("Balance:");
        jPanel1.add(lbl_balance, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 150, 60, -1));

        txt_balance.setBackground(new java.awt.Color(240, 240, 240));
        txt_balance.setEnabled(false);
        jPanel1.add(txt_balance, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 200, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 370, 300));

        getAccessibleContext().setAccessibleName("Payment");

        setSize(new java.awt.Dimension(426, 384));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_bpaymentdoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bpaymentdoneActionPerformed
        
        String strDepositAmount = txt_amountdeposit.getText();
        if ("".equals(strDepositAmount)) {
            //Show error message no deposit amount entered
        } else {
            this.weddingDetails.setStatus(Constants.WeddingDetailsStatus.DEPOSIT);
            this.weddingDetails.setAmountDeposit(Double.parseDouble(strDepositAmount));
            this.weddingDetails.setBalance(Double.parseDouble(txt_balance.getText()));
            if (this.weddingDetails.update()) {
                this.parentFrame.showDataToWeddingBookTable();
                this.parentFrame.clearTextField();
                this.parentFrame.paymentButtonSetup();
                dispose();
            }

        }

    }//GEN-LAST:event_btn_bpaymentdoneActionPerformed

    
    private void txt_amountdepositKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_amountdepositKeyPressed
        // TODO add your handling code here:
        Double amountDeposit = 0.0;
        String strAmountDeposit = txt_amountdeposit.getText();

        if (!"".equals(strAmountDeposit)) {
            amountDeposit = Double.parseDouble(strAmountDeposit);
        }

        Double balance = Constants.Payment.COST - amountDeposit;
        txt_balance.setText(String.format("%.2f", balance));

    }//GEN-LAST:event_txt_amountdepositKeyPressed

    private void btn_bpaymentcancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bpaymentcancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btn_bpaymentcancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Payment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_bpaymentcancel;
    private javax.swing.JButton btn_bpaymentdone;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JLabel lbl_amountdeposit;
    private javax.swing.JLabel lbl_balance;
    private javax.swing.JTextField txt_amountdeposit;
    private javax.swing.JTextField txt_balance;
    // End of variables declaration//GEN-END:variables
}
