/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ViewsAdmin;

import Database.MySql;
import ViewsNonAdmin.WeddingDetails;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import net.proteanit.sql.DbUtils;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;


/**
 *
 * @author LopezLaps
 */
public class Reports extends javax.swing.JFrame {

    public String driver = "com.mysql.jdbc.Driver";
    public Connection connection = null;
    public PreparedStatement preparedStatement = null;
    public ResultSet resultSet = null;
    /**
     * Creates new form Reports
     */
    public Reports() {
        initComponents();
        Themes.Theme.setIcon(this);
        this.showDataToWeddingBookTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table_user = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txt_search = new javax.swing.JTextField();
        btn_go = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_rwdbookername = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_rwddateofwedding = new javax.swing.JTextField();
        txt_rwdfullnameofbride = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_rwdfullnameofgroom = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_rwdaddress = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_rwdcity = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_rwdcontactnumber = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txt_rpclocationgettingready = new javax.swing.JTextField();
        txt_rpclocationceremony = new javax.swing.JTextField();
        txt_rpclocationphotoshoot = new javax.swing.JTextField();
        txt_rpclocationreception = new javax.swing.JTextField();
        txt_rpctimegettingready = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txt_rpctimeceremony = new javax.swing.JTextField();
        txt_rpctimephotoshoot = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        txt_rpctimereception = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ta_roispecialrequestnotes = new javax.swing.JTextArea();
        txt_roinumberofguest = new javax.swing.JTextField();
        btn_rpayment = new javax.swing.JButton();
        btn_rupdate = new javax.swing.JButton();
        btn_rbacktohome = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table_user.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table_user.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_userMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_user);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 350, 400));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Search");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 50, 20));

        txt_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_searchKeyPressed(evt);
            }
        });
        getContentPane().add(txt_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 210, 30));

        btn_go.setBackground(new java.awt.Color(255, 0, 153));
        btn_go.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_go.setForeground(new java.awt.Color(255, 255, 255));
        btn_go.setText("GO");
        btn_go.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_goActionPerformed(evt);
            }
        });
        getContentPane().add(btn_go, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, 60, 30));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 153));
        jLabel2.setText("                    WEDDING DETAILS");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 340, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 153));
        jLabel3.setText("BOOKER NAME:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 90, -1));

        txt_rwdbookername.setEnabled(false);
        jPanel1.add(txt_rwdbookername, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 130, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 153));
        jLabel4.setText("DATE OF WEDDING:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 150, 30));

        txt_rwddateofwedding.setEnabled(false);
        jPanel1.add(txt_rwddateofwedding, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 130, 30));

        txt_rwdfullnameofbride.setEnabled(false);
        jPanel1.add(txt_rwdfullnameofbride, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 130, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 153));
        jLabel5.setText("FULL NAME OF THE BRIDE:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 170, 30));

        txt_rwdfullnameofgroom.setEnabled(false);
        jPanel1.add(txt_rwdfullnameofgroom, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 130, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 153));
        jLabel6.setText("FULL NAME OF THE GROOM:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 170, 30));

        txt_rwdaddress.setEnabled(false);
        jPanel1.add(txt_rwdaddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, 130, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 153));
        jLabel7.setText("ADDRESS:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, 100, 30));

        txt_rwdcity.setEnabled(false);
        jPanel1.add(txt_rwdcity, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 400, 130, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 0, 153));
        jLabel8.setText("CITY:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 400, 80, 30));

        txt_rwdcontactnumber.setEnabled(false);
        jPanel1.add(txt_rwdcontactnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 470, 130, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 153));
        jLabel9.setText("CONTACT #:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 470, 110, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, 360, 560));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 0, 153));
        jLabel10.setText("                       Photography Coverage");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 430, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 0, 153));
        jLabel11.setText("Location:");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, -1, 30));

        txt_rpclocationgettingready.setEnabled(false);
        jPanel2.add(txt_rpclocationgettingready, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, 130, 30));

        txt_rpclocationceremony.setEnabled(false);
        jPanel2.add(txt_rpclocationceremony, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, 130, 30));

        txt_rpclocationphotoshoot.setEnabled(false);
        jPanel2.add(txt_rpclocationphotoshoot, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, 130, 30));

        txt_rpclocationreception.setEnabled(false);
        jPanel2.add(txt_rpclocationreception, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, 130, 30));

        txt_rpctimegettingready.setEnabled(false);
        jPanel2.add(txt_rpctimegettingready, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 50, 30));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 0, 153));
        jLabel15.setText("Time:");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, -1, 30));

        txt_rpctimeceremony.setEnabled(false);
        jPanel2.add(txt_rpctimeceremony, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 50, 30));

        txt_rpctimephotoshoot.setEnabled(false);
        jPanel2.add(txt_rpctimephotoshoot, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 50, 30));

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 0, 153));
        jLabel34.setText("Location:");
        jPanel2.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, -1, 30));

        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 0, 153));
        jLabel35.setText("Location:");
        jPanel2.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, -1, 30));

        jLabel36.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 0, 153));
        jLabel36.setText("Location:");
        jPanel2.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, -1, 30));

        txt_rpctimereception.setEnabled(false);
        jPanel2.add(txt_rpctimereception, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 50, 30));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 0, 153));
        jLabel18.setText("Time:");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, -1, 30));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 0, 153));
        jLabel19.setText("Time:");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, -1, 30));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 0, 153));
        jLabel20.setText("Time:");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, -1, 30));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 0, 153));
        jLabel12.setText("RECEPTION");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, 20));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 0, 153));
        jLabel13.setText("GETTING READY ");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, 20));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 0, 153));
        jLabel14.setText("CEREMONY");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 70, 20));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 0, 153));
        jLabel16.setText("PHOTOSHOOT");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, 20));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 10, 460, 300));

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 0, 153));
        jLabel26.setText("                           Other Information");
        jPanel4.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, -1));

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 0, 153));
        jLabel27.setText("Number of Guest:");
        jPanel4.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 100, -1));

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 0, 153));
        jLabel28.setText("Special/Request/Notes:");
        jPanel4.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 150, -1));

        ta_roispecialrequestnotes.setColumns(20);
        ta_roispecialrequestnotes.setRows(5);
        ta_roispecialrequestnotes.setEnabled(false);
        jScrollPane2.setViewportView(ta_roispecialrequestnotes);

        jPanel4.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 310, 100));

        txt_roinumberofguest.setEnabled(false);
        jPanel4.add(txt_roinumberofguest, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 130, 30));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 320, 460, 250));

        btn_rpayment.setBackground(new java.awt.Color(255, 0, 153));
        btn_rpayment.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_rpayment.setForeground(new java.awt.Color(255, 255, 255));
        btn_rpayment.setText("GO TO PAYMENT");
        btn_rpayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_rpaymentActionPerformed(evt);
            }
        });
        getContentPane().add(btn_rpayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 530, 350, 40));

        btn_rupdate.setBackground(new java.awt.Color(255, 0, 153));
        btn_rupdate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_rupdate.setForeground(new java.awt.Color(255, 255, 255));
        btn_rupdate.setText("UPDATE");
        btn_rupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_rupdateActionPerformed(evt);
            }
        });
        getContentPane().add(btn_rupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 490, 80, 30));

        btn_rbacktohome.setBackground(new java.awt.Color(255, 0, 153));
        btn_rbacktohome.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_rbacktohome.setForeground(new java.awt.Color(255, 255, 255));
        btn_rbacktohome.setText("HOME");
        btn_rbacktohome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_rbacktohomeActionPerformed(evt);
            }
        });
        getContentPane().add(btn_rbacktohome, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, 80, 30));

        setSize(new java.awt.Dimension(1274, 634));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    public void frameClose() {
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        WindowEvent winClosingEvent = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }
    
    private void btn_rbacktohomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_rbacktohomeActionPerformed
        new Views.Home().setVisible(true);
        //dispose();
    }//GEN-LAST:event_btn_rbacktohomeActionPerformed

    private void showDataToWeddingBookTable() {
        DataObjects.WeddingDetails wedDetails = new DataObjects.WeddingDetails();
        resultSet = wedDetails.getBookerBrideAndGroom();
        table_user.setModel(DbUtils.resultSetToTableModel(resultSet));
        ((DefaultTableCellRenderer) table_user.getTableHeader().getDefaultRenderer()).setHorizontalAlignment(JLabel.LEFT);
    }

    private void searchAndShowDataToWeddingBookTable() {
        String searchKeyWords = txt_search.getText();
        DataObjects.WeddingDetails wedDetails = new DataObjects.WeddingDetails();
        resultSet = wedDetails.getBookerBrideAndGroom(searchKeyWords);
        table_user.setModel(DbUtils.resultSetToTableModel(resultSet));
        ((DefaultTableCellRenderer) table_user.getTableHeader().getDefaultRenderer()).setHorizontalAlignment(JLabel.LEFT);
    }


    private void btn_goActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_goActionPerformed
        this.searchAndShowDataToWeddingBookTable();
    }//GEN-LAST:event_btn_goActionPerformed

    private void txt_searchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_searchKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            this.searchAndShowDataToWeddingBookTable();
        }
        System.out.println("Key code being press by the user :>" + evt.getKeyCode());
    }//GEN-LAST:event_txt_searchKeyPressed

    private void table_userMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_userMouseClicked

        int row = table_user.getSelectedRow();
        String id = (table_user.getModel().getValueAt(row, 0).toString());

        System.out.println(id);
        DataObjects.WeddingDetails wedDetails = new DataObjects.WeddingDetails();
        ResultSet rs = wedDetails.getWeddingDetailsById(id);

        try {
            if (rs.next()) {
                this.txt_rwdbookername.setText(rs.getString("bookername"));
                this.txt_rwddateofwedding.setText(rs.getString("dateofwedding"));
                this.txt_rwdfullnameofbride.setText(rs.getString("fullnameofthebride"));
                this.txt_rwdfullnameofgroom.setText(rs.getString("fullnameofthegroom"));
                this.txt_rwdaddress.setText(rs.getString("address"));
                this.txt_rwdcity.setText(rs.getString("city"));
                this.txt_rwdcontactnumber.setText(rs.getString("contactno"));

                this.txt_rpctimegettingready.setText(rs.getString("gettingreadytime"));
                this.txt_rpclocationgettingready.setText(rs.getString("gettingreadylocation"));
                this.txt_rpctimeceremony.setText(rs.getString("ceremonytime"));
                this.txt_rpclocationceremony.setText(rs.getString("ceremonylocation"));
                this.txt_rpctimephotoshoot.setText(rs.getString("photoshoottime"));
                this.txt_rpclocationphotoshoot.setText(rs.getString("photoshootlocation"));
                this.txt_rpctimereception.setText(rs.getString("receptiontime"));
                this.txt_rpclocationreception.setText(rs.getString("receptionlocation"));

                this.txt_roinumberofguest.setText(rs.getString("numberofguest"));
                this.ta_roispecialrequestnotes.setText(rs.getString("special_request_notes"));

            }
        } catch (SQLException ex) {
            Logger.getLogger(Reports.class.getName()).log(Level.SEVERE, null, ex);
        }

        this.disableTextField();
    }//GEN-LAST:event_table_userMouseClicked

    private DataObjects.WeddingDetails getBookingInformation() {
        DataObjects.WeddingDetails wedDetails = new DataObjects.WeddingDetails();

        wedDetails.setBookerName(this.txt_rwdbookername.getText());
        wedDetails.setDateOfWedding(this.txt_rwddateofwedding.getText());
        wedDetails.setFullnameOfTheBride(this.txt_rwdfullnameofbride.getText());
        wedDetails.setFullnameOfTheGroom(this.txt_rwdfullnameofgroom.getText());
        wedDetails.setAddress(this.txt_rwdaddress.getText());
        wedDetails.setCity(this.txt_rwdcity.getText());
        wedDetails.setContactNo(this.txt_rwdcontactnumber.getText());

        wedDetails.setGettingReadyTime(txt_rpctimegettingready.getText());
        wedDetails.setGettingReadyLocation(txt_rpclocationgettingready.getText());
        wedDetails.setCeremonyTime(txt_rpctimeceremony.getText());
        wedDetails.setCeremonyLocation(txt_rpclocationceremony.getText());
        wedDetails.setPhotoshootTime(txt_rpctimephotoshoot.getText());
        wedDetails.setPhotoshootLocation(txt_rpclocationphotoshoot.getText());
        wedDetails.setReceptionTime(txt_rpctimereception.getText());
        wedDetails.setReceptionLocation(txt_rpclocationreception.getText());

        wedDetails.setNumberOfGuest(txt_roinumberofguest.getText());
        wedDetails.setSpecialRequestNotes(ta_roispecialrequestnotes.getText());

        //DataObjects.WeddingDetails.save(wedDetails);
        return wedDetails;
    }

    public void disableTextField() {
        this.txt_rwdbookername.setEnabled(true);
        this.txt_rwddateofwedding.setEnabled(true);
        this.txt_rwdfullnameofbride.setEnabled(true);
        this.txt_rwdfullnameofgroom.setEnabled(true);
        this.txt_rwdaddress.setEnabled(true);
        this.txt_rwdcity.setEnabled(true);
        this.txt_rwdcontactnumber.setEnabled(true);

        this.txt_rpctimegettingready.setEnabled(true);
        this.txt_rpclocationgettingready.setEnabled(true);
        this.txt_rpctimeceremony.setEnabled(true);
        this.txt_rpclocationceremony.setEnabled(true);
        this.txt_rpctimephotoshoot.setEnabled(true);
        this.txt_rpclocationphotoshoot.setEnabled(true);
        this.txt_rpctimereception.setEnabled(true);
        this.txt_rpclocationreception.setEnabled(true);

        this.txt_roinumberofguest.setEnabled(true);
        this.ta_roispecialrequestnotes.setEnabled(true);
    }

    public void clearTextField() {
        this.txt_rwdbookername.setText("");
        this.txt_rwddateofwedding.setText("");
        this.txt_rwdfullnameofbride.setText("");
        this.txt_rwdfullnameofgroom.setText("");
        this.txt_rwdaddress.setText("");
        this.txt_rwdcity.setText("");
        this.txt_rwdcontactnumber.setText("");

        this.txt_rpctimegettingready.setText("");
        this.txt_rpclocationgettingready.setText("");
        this.txt_rpctimeceremony.setText("");
        this.txt_rpclocationceremony.setText("");
        this.txt_rpctimephotoshoot.setText("");
        this.txt_rpclocationphotoshoot.setText("");
        this.txt_rpctimereception.setText("");
        this.txt_rpclocationreception.setText("");

        this.txt_roinumberofguest.setText("");
        this.ta_roispecialrequestnotes.setText("");
    }

    private void btn_rupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_rupdateActionPerformed
        DataObjects.WeddingDetails wedDetails = this.getBookingInformation();

        int row = table_user.getSelectedRow();
        Integer id = Integer.parseInt(table_user.getModel().getValueAt(row, 0).toString());
        wedDetails.setId(id);
        if (wedDetails.update()) {
            this.showDataToWeddingBookTable();
            this.clearTextField();
        }

    }//GEN-LAST:event_btn_rupdateActionPerformed

    private void btn_rpaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_rpaymentActionPerformed
        //        ViewsAdmin.Login login = new ViewsAdmin.Login(this, true);
          //      login.setVisible(true);
        ViewsAdmin.Payment payment = new ViewsAdmin.Payment(this, true);
        payment.setVisible(true);
    }//GEN-LAST:event_btn_rpaymentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reports().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_go;
    private javax.swing.JButton btn_rbacktohome;
    private javax.swing.JButton btn_rpayment;
    private javax.swing.JButton btn_rupdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea ta_roispecialrequestnotes;
    private javax.swing.JTable table_user;
    private javax.swing.JTextField txt_roinumberofguest;
    private javax.swing.JTextField txt_rpclocationceremony;
    private javax.swing.JTextField txt_rpclocationgettingready;
    private javax.swing.JTextField txt_rpclocationphotoshoot;
    private javax.swing.JTextField txt_rpclocationreception;
    private javax.swing.JTextField txt_rpctimeceremony;
    private javax.swing.JTextField txt_rpctimegettingready;
    private javax.swing.JTextField txt_rpctimephotoshoot;
    private javax.swing.JTextField txt_rpctimereception;
    private javax.swing.JTextField txt_rwdaddress;
    private javax.swing.JTextField txt_rwdbookername;
    private javax.swing.JTextField txt_rwdcity;
    private javax.swing.JTextField txt_rwdcontactnumber;
    private javax.swing.JTextField txt_rwddateofwedding;
    private javax.swing.JTextField txt_rwdfullnameofbride;
    private javax.swing.JTextField txt_rwdfullnameofgroom;
    private javax.swing.JTextField txt_search;
    // End of variables declaration//GEN-END:variables
}
